project_name: icann-client

before:
  hooks:
    - go mod tidy

builds:
  - id: icann
    main: ./cmd/icann
    binary: icann
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: icann-archives
    builds: [icann]
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  draft: false
  prerelease: auto

brews:
  - name: icann
    repository:
      owner: onasunnymorning
      name: homebrew-tap
      branch: main
    commit_author:
      name: goreleaserbot
      email: goreleaser@github.com
    homepage: https://github.com/onasunnymorning/icann-client
    description: "ICANN MOSAPI and RRI CLI"
    license: MIT
    # Install the binary; bottles will be handled by Homebrew infra when/if configured.
    install: |
      bin.install "icann"
    test: |
      system "#{bin}/icann", "--help"
