name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: true

      - name: Run tests (race)
        run: go test ./... -race

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          # IMPORTANT: If set, TAP_GITHUB_TOKEN must have Contents: Read & write on BOTH repos:
          # - onasunnymorning/icann-client (to create the release)
          # - onasunnymorning/homebrew-tap (to push the formula)
          # Otherwise, the default GITHUB_TOKEN will only publish the release and will NOT push to the tap.
          GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
